import re, collections

CSS_PROPERTIES_LIST = [
    'content',
    'all',
    'revert',
    'will-change',
    'orientation',
    'position',
    'float',
    'clear',
    'display',
    'box-sizing',
    'flex',
    'flex-direction',
    'order',
    'flex-flow',
    'flex-wrap',
    'flex-grow',
    'flex-shrink',
    'flex-basis',
    'align-content',
    'align-items',
    'justify-content',
    'align-self',
    'vertical-align',
    'table-layout',
    'grid',
    'grid-area',
    'grid-auto-columns',
    'grid-auto-flow',
    'grid-auto-rows',
    'grid-column',
    'grid-column-end',
    'grid-column-gap',
    'grid-column-start',
    'grid-gap',
    'grid-row',
    'grid-row-end',
    'grid-row-gap',
    'grid-row-start',
    'grid-template',
    'grid-template-areas',
    'grid-template-columns',
    'grid-template-rows',
    'columns',
    'column-count',
    'column-width',
    'column-fill',
    'column-gap',
    'column-rule',
    'column-rule-color',
    'column-rule-style',
    'column-rule-width',
    'column-span',
    'shape-outside',
    'shape-margin',
    'shape-image-threshold',
    'top',
    'bottom',
    'left',
    'right',
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'margin',
    'margin-top',
    'margin-bottom',
    'margin-left',
    'margin-right',
    'padding',
    'padding-top',
    'padding-bottom',
    'padding-left',
    'padding-right',
    'transform',
    'transform-box',
    'transform-origin',
    'transform-style',
    'object-fit',
    'object-position',
    'writing-mode',
    'block-size',
    'inline-size',
    'min-block-size',
    'max-block-size',
    'min-inline-size',
    'max-inline-size',
    'margin-block-start',
    'margin-block-end',
    'margin-inline-start',
    'margin-inline-end',
    'padding-block-start',
    'padding-block-end',
    'padding-inline-start',
    'padding-inline-end',
    'offset-block-start',
    'offset-block-end',
    'offset-inline-start',
    'offset-inline-end',
    'border-collapse',
    'color',
    'background',
    'background-origin',
    'background-color',
    'background-image',
    'background-attachment',
    'background-position',
    'background-size',
    'background-clip',
    'background-repeat',
    'background-blend-mode',
    'mix-blend-mode',
    'filter',
    'border',
    'border-color',
    'border-width',
    'border-style',
    'border-radius',
    'border-spacing',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-bottom-left-radius',
    'border-bottom-right-radius',
    'border-top',
    'border-bottom',
    'border-left',
    'border-right',
    'border-top-color',
    'border-bottom-color',
    'border-left-color',
    'border-right-color',
    'border-top-width',
    'border-bottom-width',
    'border-left-width',
    'border-right-width',
    'border-top-style',
    'border-bottom-style',
    'border-left-style',
    'border-right-style',
    'border-image',
    'border-image-source',
    'border-image-width',
    'border-image-outset',
    'border-image-slice',
    'border-image-repeat',
    'border-block-start',
    'border-block-start-color',
    'border-block-start-style',
    'border-block-start-width',
    'border-block-end',
    'border-block-end-color',
    'border-block-end-style',
    'border-block-end-width',
    'border-inline-start',
    'border-inline-start-color',
    'border-inline-start-style',
    'border-inline-start-width',
    'border-inline-end',
    'border-inline-end-color',
    'border-inline-end-style',
    'border-inline-end-width',
    'outline',
    'outline-color',
    'outline-width',
    'outline-style',
    'outline-offset',
    'box-shadow',
    'mask',
    'mask-clip',
    'mask-composite',
    'mask-image',
    'mask-mode',
    'mask-origin',
    'mask-position',
    'mask-repeat',
    'mask-size',
    'mask-type',
    'opacity',
    'visibility',
    'backface-visibility',
    'clip',
    'clip-path',
    'empty-cells',
    'box-decoration-break',
    'unicode-range',
    'font',
    'font-family',
    'font-size',
    'font-size-adjust',
    'font-weight',
    'font-style',
    'font-feature-settings',
    'font-kerning',
    'font-language-override',
    'font-stretch',
    'font-synthesis',
    'font-variant',
    'font-variant-alternates',
    'font-variant-caps',
    'font-variant-east-asian',
    'font-variant-ligatures',
    'font-variant-numeric',
    'font-variant-position',
    'direction',
    'unicode-bidi',
    'text-align',
    'text-align-last',
    'text-transform',
    'line-height',
    'letter-spacing',
    'tab-size',
    'text-indent',
    'text-orientation',
    'text-decoration',
    'text-decoration-color',
    'text-decoration-style',
    'text-decoration-line',
    'text-emphasis',
    'text-emphasis-color',
    'text-emphasis-style',
    'text-emphasis-position',
    'text-overflow',
    'text-shadow',
    'text-underline-position',
    'text-rendering',
    'text-combine-upright',
    'white-space',
    'line-break',
    'word-break',
    'word-spacing',
    'word-wrap',
    'hyphens',
    'orphans',
    'widows',
    'quotes',
    'ruby-position',
    'ruby-align',
    'ruby-merge',
    'cursor',
    'pointer-events',
    'touch-action',
    'overflow',
    'overflow-x',
    'overflow-y',
    'overflow-wrap',
    'scroll-behavior',
    'scroll-snap-type',
    'scroll-snap-coordinate',
    'scroll-snap-destination',
    'list-style',
    'list-style-image',
    'list-style-position',
    'list-style-type',
    'range',
    'counter-increment',
    'counter-reset',
    'system',
    'fallback',
    'pad',
    'prefix',
    'suffix',
    'symbols',
    'additive-symbols',
    'negative',
    'speak-as',
    'caption-side',
    'break-before',
    'break-inside',
    'break-after',
    'page-break-before',
    'page-break-inside',
    'page-break-after',
    'image-orientation',
    'image-rendering',
    'image-resolution',
    'ime-mode',
    'isolation',
    'perspective',
    'perspective-origin',
    'resize',
    'zoom',
    'min-zoom',
    'max-zoom',
    'user-zoom',
    'animation',
    'animation-name',
    'animation-duration',
    'animation-timing-function',
    'animation-delay',
    'animation-play-state',
    'animation-direction',
    'animation-fill-mode',
    'animation-iteration-count',
    'transition',
    'transition-duration',
    'transition-timing-function',
    'transition-delay',
    'transition-property',
    'z-index',
]

CSS_PROPERTIES_MAP = collections.defaultdict(lambda: None)

PROPERTY_REGEX = re.compile('^\s*([-\w]+):.*;\s*$')

for index in range(len(CSS_PROPERTIES_LIST)):
    CSS_PROPERTIES_MAP[CSS_PROPERTIES_LIST[index]] = -index

def get_line_index(line):
    word_match = PROPERTY_REGEX.match(line).group(1)
    return CSS_PROPERTIES_MAP[word_match]

def cmp_lines(a, b):
    match_a = get_line_index(a)
    match_b = get_line_index(b)
    return -cmp(match_a, match_b)

def find_end(lines, index):
    cur_result = index
    while index < len(lines):
        if len(lines[index].strip()) == 0:
            pass
        elif PROPERTY_REGEX.match(lines[index]):
            cur_result = index
        else:
            break
        index += 1
    return cur_result

def transform(lines):
    cur_line = 0

    result_block = []

    while cur_line < len(lines):
        if PROPERTY_REGEX.match(lines[cur_line]):
            block_end = find_end(lines, cur_line)

            new_block = sorted([line for line in lines[cur_line:block_end + 1] if len(line) > 0], cmp = cmp_lines)
            result_block.extend(new_block)

            cur_line = block_end + 1
        else:
            result_block.append(lines[cur_line])
            cur_line += 1

    return result_block

import vim

first_line = int(vim.eval('a:firstline'))
last_line =  int(vim.eval('a:lastline'))

lines = list(vim.current.buffer.range(first_line, last_line))

vim.current.buffer[first_line - 1:last_line] = transform(lines)
